#[derive(Debug, Clone)]
pub struct BuiltinFunction {
    pub name: &'static str,
    pub signature: &'static str,
    pub description: &'static str,
    pub params: &'static [ParamInfo],
    pub return_type: &'static str,
    pub category: Category,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    Math,
    String,
    List,
    Entity,
    SelectionSet,
    Conversion,
    FileIO,
    Display,
    Geometry,
    ControlFlow,
    ErrorHandling,
    TypeChecking,
    UserInput,
    Symbol,
    Misc,
}

#[derive(Debug, Clone)]
pub struct ParamInfo {
    pub name: &'static str,
    pub description: &'static str,
}

pub fn lookup(name: &str) -> Option<&'static BuiltinFunction> {
    let upper = name.to_uppercase();
    BUILTINS.iter().find(|b| b.name == upper)
}

pub fn all() -> &'static [BuiltinFunction] {
    &BUILTINS
}

pub fn by_prefix(prefix: &str) -> Vec<&'static BuiltinFunction> {
    let upper = prefix.to_uppercase();
    BUILTINS
        .iter()
        .filter(|b| b.name.starts_with(&upper))
        .collect()
}

macro_rules! params {
    () => { &[] };
    ( $( $name:expr => $desc:expr ),+ $(,)? ) => {
        &[ $( ParamInfo { name: $name, description: $desc } ),+ ]
    };
}

static BUILTINS: &[BuiltinFunction] = &[
    // ===== Math =====
    BuiltinFunction {
        name: "+",
        signature: "(+ number number ...)",
        description: "Returns the sum of all numbers",
        params: params!("number" => "Numbers to add"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "-",
        signature: "(- number number ...)",
        description: "Subtracts the second and subsequent numbers from the first",
        params: params!("number" => "Numbers to subtract"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "*",
        signature: "(* number number ...)",
        description: "Returns the product of all numbers",
        params: params!("number" => "Numbers to multiply"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "/",
        signature: "(/ number number ...)",
        description: "Divides the first number by the subsequent numbers",
        params: params!("number" => "Numbers for division"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "1+",
        signature: "(1+ number)",
        description: "Returns the argument plus one",
        params: params!("number" => "Number to increment"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "1-",
        signature: "(1- number)",
        description: "Returns the argument minus one",
        params: params!("number" => "Number to decrement"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "ABS",
        signature: "(abs number)",
        description: "Returns the absolute value of number",
        params: params!("number" => "Number"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "ATAN",
        signature: "(atan number1 [number2])",
        description: "Returns the arctangent of a number in radians",
        params: params!("number1" => "Number or Y component", "number2" => "Optional X component"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "COS",
        signature: "(cos angle)",
        description: "Returns the cosine of an angle in radians",
        params: params!("angle" => "Angle in radians"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "EXP",
        signature: "(exp number)",
        description: "Returns e raised to the power of number",
        params: params!("number" => "Exponent"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "EXPT",
        signature: "(expt base power)",
        description: "Returns base raised to the specified power",
        params: params!("base" => "Base number", "power" => "Exponent"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "FIX",
        signature: "(fix number)",
        description: "Returns the integer conversion of number (truncation)",
        params: params!("number" => "Number to truncate"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "FLOAT",
        signature: "(float number)",
        description: "Returns the real conversion of number",
        params: params!("number" => "Number to convert"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "GCD",
        signature: "(gcd int1 int2)",
        description: "Returns the greatest common divisor of two integers",
        params: params!("int1" => "First integer", "int2" => "Second integer"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "LOG",
        signature: "(log number)",
        description: "Returns the natural log of number",
        params: params!("number" => "Positive number"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "MAX",
        signature: "(max number number ...)",
        description: "Returns the largest of the given numbers",
        params: params!("number" => "Numbers to compare"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "MIN",
        signature: "(min number number ...)",
        description: "Returns the smallest of the given numbers",
        params: params!("number" => "Numbers to compare"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "MINUSP",
        signature: "(minusp number)",
        description: "Returns T if number is negative",
        params: params!("number" => "Number to test"),
        return_type: "T/nil",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "REM",
        signature: "(rem number1 number2 ...)",
        description: "Returns the remainder of dividing number1 by number2",
        params: params!("number1" => "Dividend", "number2" => "Divisor"),
        return_type: "number",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "SIN",
        signature: "(sin angle)",
        description: "Returns the sine of an angle in radians",
        params: params!("angle" => "Angle in radians"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "SQRT",
        signature: "(sqrt number)",
        description: "Returns the square root of number",
        params: params!("number" => "Non-negative number"),
        return_type: "real",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "ZEROP",
        signature: "(zerop number)",
        description: "Returns T if number is zero",
        params: params!("number" => "Number to test"),
        return_type: "T/nil",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "LOGAND",
        signature: "(logand int1 int2 ...)",
        description: "Returns the bitwise AND of integers",
        params: params!("int" => "Integers"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "LOGIOR",
        signature: "(logior int1 int2 ...)",
        description: "Returns the bitwise OR of integers",
        params: params!("int" => "Integers"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "LSH",
        signature: "(lsh int numbits)",
        description: "Returns the logical bitwise shift of int by numbits",
        params: params!("int" => "Integer to shift", "numbits" => "Number of bits to shift"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "BOOLE",
        signature: "(boole func int1 int2)",
        description: "Serves as a general bitwise Boolean function",
        params: params!("func" => "Boolean function code (0-15)", "int1" => "First integer", "int2" => "Second integer"),
        return_type: "integer",
        category: Category::Math,
    },
    BuiltinFunction {
        name: "~",
        signature: "(~ int)",
        description: "Returns the bitwise NOT (ones complement) of int",
        params: params!("int" => "Integer"),
        return_type: "integer",
        category: Category::Math,
    },
    // ===== String =====
    BuiltinFunction {
        name: "STRCAT",
        signature: "(strcat string1 [string2] ...)",
        description: "Concatenates multiple strings into one",
        params: params!("string" => "Strings to concatenate"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "STRLEN",
        signature: "(strlen [string] ...)",
        description: "Returns the number of characters in a string",
        params: params!("string" => "String to measure"),
        return_type: "integer",
        category: Category::String,
    },
    BuiltinFunction {
        name: "SUBSTR",
        signature: "(substr string start [length])",
        description: "Returns a substring of string",
        params: params!("string" => "Source string", "start" => "Starting position (1-based)", "length" => "Optional length"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "STRCASE",
        signature: "(strcase string [which])",
        description: "Returns string converted to upper or lower case",
        params: params!("string" => "String to convert", "which" => "nil=upper, T=lower"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "ASCII",
        signature: "(ascii string)",
        description: "Returns the ASCII code of the first character",
        params: params!("string" => "String"),
        return_type: "integer",
        category: Category::String,
    },
    BuiltinFunction {
        name: "CHR",
        signature: "(chr integer)",
        description: "Returns the character with the given ASCII code",
        params: params!("integer" => "ASCII code"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "WCMATCH",
        signature: "(wcmatch string pattern)",
        description: "Performs a wildcard pattern match on a string",
        params: params!("string" => "String to test", "pattern" => "Wildcard pattern"),
        return_type: "T/nil",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-TRIM",
        signature: "(vl-string-trim char-set string)",
        description: "Removes specified characters from both ends of string",
        params: params!("char-set" => "Characters to trim", "string" => "String to trim"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-LEFT-TRIM",
        signature: "(vl-string-left-trim char-set string)",
        description: "Removes specified characters from the beginning of string",
        params: params!("char-set" => "Characters to trim", "string" => "String to trim"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-RIGHT-TRIM",
        signature: "(vl-string-right-trim char-set string)",
        description: "Removes specified characters from the end of string",
        params: params!("char-set" => "Characters to trim", "string" => "String to trim"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-SEARCH",
        signature: "(vl-string-search pattern string [start-pos])",
        description: "Searches for the specified pattern in a string",
        params: params!("pattern" => "Pattern to search for", "string" => "String to search", "start-pos" => "Optional starting position"),
        return_type: "integer/nil",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-SUBST",
        signature: "(vl-string-subst new-str pattern string [start-pos])",
        description: "Substitutes one string for another within a string",
        params: params!("new-str" => "Replacement string", "pattern" => "Pattern to replace", "string" => "Source string", "start-pos" => "Optional starting position"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-TRANSLATE",
        signature: "(vl-string-translate source-set dest-set string)",
        description: "Replaces characters in a string with specified characters",
        params: params!("source-set" => "Characters to replace", "dest-set" => "Replacement characters", "string" => "Source string"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-POSITION",
        signature: "(vl-string-position char-code string [start-pos [from-end]])",
        description: "Returns the position of a character in a string",
        params: params!("char-code" => "ASCII code of character", "string" => "String to search", "start-pos" => "Optional starting position", "from-end" => "Optional search from end"),
        return_type: "integer/nil",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-STRING-MISMATCH",
        signature: "(vl-string-mismatch str1 str2 [pos1 [pos2]])",
        description: "Returns the length of the common prefix of two strings",
        params: params!("str1" => "First string", "str2" => "Second string"),
        return_type: "integer",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-PRINC-TO-STRING",
        signature: "(vl-princ-to-string object)",
        description: "Returns the string representation of an object (as princ would display it)",
        params: params!("object" => "Object to convert"),
        return_type: "string",
        category: Category::String,
    },
    BuiltinFunction {
        name: "VL-PRIN1-TO-STRING",
        signature: "(vl-prin1-to-string object)",
        description: "Returns the string representation of an object (as prin1 would display it)",
        params: params!("object" => "Object to convert"),
        return_type: "string",
        category: Category::String,
    },
    // ===== List =====
    BuiltinFunction {
        name: "CAR",
        signature: "(car list)",
        description: "Returns the first element of a list",
        params: params!("list" => "A list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CDR",
        signature: "(cdr list)",
        description: "Returns all but the first element of a list",
        params: params!("list" => "A list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CAAR",
        signature: "(caar list)",
        description: "Equivalent to (car (car list))",
        params: params!("list" => "A nested list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CADR",
        signature: "(cadr list)",
        description: "Equivalent to (car (cdr list)), returns the second element",
        params: params!("list" => "A list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CDAR",
        signature: "(cdar list)",
        description: "Equivalent to (cdr (car list))",
        params: params!("list" => "A nested list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CDDR",
        signature: "(cddr list)",
        description: "Equivalent to (cdr (cdr list))",
        params: params!("list" => "A list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CADDR",
        signature: "(caddr list)",
        description: "Equivalent to (car (cdr (cdr list))), returns the third element",
        params: params!("list" => "A list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CONS",
        signature: "(cons element list)",
        description: "Adds an element to the beginning of a list or creates a dotted pair",
        params: params!("element" => "Element to add", "list" => "Existing list or atom"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "LIST",
        signature: "(list expr ...)",
        description: "Creates a list from the given expressions",
        params: params!("expr" => "Expressions to form the list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "APPEND",
        signature: "(append list ...)",
        description: "Combines multiple lists into one",
        params: params!("list" => "Lists to concatenate"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "LENGTH",
        signature: "(length list)",
        description: "Returns the number of elements in a list",
        params: params!("list" => "A list"),
        return_type: "integer",
        category: Category::List,
    },
    BuiltinFunction {
        name: "NTH",
        signature: "(nth n list)",
        description: "Returns the nth element of a list (0-based)",
        params: params!("n" => "Zero-based index", "list" => "A list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "LAST",
        signature: "(last list)",
        description: "Returns the last element of a list",
        params: params!("list" => "A list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "MEMBER",
        signature: "(member expr list)",
        description: "Searches a list for an occurrence of an expression and returns the rest of the list",
        params: params!("expr" => "Expression to search for", "list" => "A list"),
        return_type: "list/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "ASSOC",
        signature: "(assoc element alist)",
        description: "Searches an association list for an element and returns that association",
        params: params!("element" => "Key to search for", "alist" => "Association list"),
        return_type: "list/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "SUBST",
        signature: "(subst new old list)",
        description: "Substitutes new item for every occurrence of old item in list",
        params: params!("new" => "New expression", "old" => "Old expression to replace", "list" => "A list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "REVERSE",
        signature: "(reverse list)",
        description: "Returns a list with elements reversed",
        params: params!("list" => "A list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "FOREACH",
        signature: "(foreach name list expr ...)",
        description: "Evaluates expressions for each element in a list",
        params: params!("name" => "Variable name", "list" => "A list", "expr" => "Expressions to evaluate"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "MAPCAR",
        signature: "(mapcar function list1 [list2] ...)",
        description: "Applies a function to successive elements of lists",
        params: params!("function" => "Function to apply", "list" => "Lists to process"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "APPLY",
        signature: "(apply function list)",
        description: "Passes a list of arguments to a function",
        params: params!("function" => "Function to apply", "list" => "Argument list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-SORT",
        signature: "(vl-sort list compare-function)",
        description: "Sorts a list using a comparison function",
        params: params!("list" => "List to sort", "compare-function" => "Comparison function"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-SORT-I",
        signature: "(vl-sort-i list compare-function)",
        description: "Sorts a list and returns index numbers of elements",
        params: params!("list" => "List to sort", "compare-function" => "Comparison function"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-REMOVE",
        signature: "(vl-remove element list)",
        description: "Removes all occurrences of an element from a list",
        params: params!("element" => "Element to remove", "list" => "Source list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-REMOVE-IF",
        signature: "(vl-remove-if predicate list)",
        description: "Removes elements that satisfy the predicate",
        params: params!("predicate" => "Test function", "list" => "Source list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-REMOVE-IF-NOT",
        signature: "(vl-remove-if-not predicate list)",
        description: "Removes elements that do not satisfy the predicate",
        params: params!("predicate" => "Test function", "list" => "Source list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-MEMBER-IF",
        signature: "(vl-member-if predicate list)",
        description: "Returns list from first element satisfying predicate",
        params: params!("predicate" => "Test function", "list" => "Source list"),
        return_type: "list/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-SOME",
        signature: "(vl-some predicate list ...)",
        description: "Checks whether the predicate is satisfied for one element",
        params: params!("predicate" => "Test function", "list" => "List(s) to check"),
        return_type: "any/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-EVERY",
        signature: "(vl-every predicate list ...)",
        description: "Checks whether the predicate is satisfied for every element",
        params: params!("predicate" => "Test function", "list" => "List(s) to check"),
        return_type: "T/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-POSITION",
        signature: "(vl-position element list)",
        description: "Returns the index of an element in a list",
        params: params!("element" => "Element to find", "list" => "Source list"),
        return_type: "integer/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "ACAD_STRLSORT",
        signature: "(acad_strlsort list)",
        description: "Sorts a list of strings alphabetically",
        params: params!("list" => "List of strings"),
        return_type: "list",
        category: Category::List,
    },
    // ===== Entity =====
    BuiltinFunction {
        name: "ENTGET",
        signature: "(entget ename [applist])",
        description: "Retrieves an entity's definition data",
        params: params!("ename" => "Entity name", "applist" => "Optional application names list for xdata"),
        return_type: "list",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTMOD",
        signature: "(entmod elist)",
        description: "Modifies the definition data of an entity",
        params: params!("elist" => "Entity association list"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTMAKE",
        signature: "(entmake [elist])",
        description: "Creates a new entity from an association list",
        params: params!("elist" => "Entity association list"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTMAKEX",
        signature: "(entmakex [elist])",
        description: "Makes a new entity and returns its name",
        params: params!("elist" => "Entity association list"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTDEL",
        signature: "(entdel ename)",
        description: "Deletes or undeletes an entity",
        params: params!("ename" => "Entity name"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTLAST",
        signature: "(entlast)",
        description: "Returns the name of the last entity in the drawing",
        params: params!(),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTNEXT",
        signature: "(entnext [ename])",
        description: "Returns the name of the next entity in the drawing",
        params: params!("ename" => "Optional entity name; if nil, returns first entity"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTSEL",
        signature: "(entsel [prompt])",
        description: "Prompts the user to select a single entity",
        params: params!("prompt" => "Optional prompt string"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "NENTSEL",
        signature: "(nentsel [prompt])",
        description: "Prompts to select an entity (with nested entity info)",
        params: params!("prompt" => "Optional prompt string"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "NENTSELP",
        signature: "(nentselp [prompt] [point])",
        description: "Similar to nentsel but with optional point argument",
        params: params!("prompt" => "Optional prompt string", "point" => "Optional selection point"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "ENTUPD",
        signature: "(entupd ename)",
        description: "Updates the screen image of an entity",
        params: params!("ename" => "Entity name"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "HANDENT",
        signature: "(handent handle)",
        description: "Returns the entity name associated with a handle",
        params: params!("handle" => "Entity handle string"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "TBLOBJNAME",
        signature: "(tblobjname table-name symbol)",
        description: "Returns the entity name of the specified symbol table entry",
        params: params!("table-name" => "Table name (e.g., \"LAYER\")", "symbol" => "Entry name"),
        return_type: "ename/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "TBLNEXT",
        signature: "(tblnext table-name [rewind])",
        description: "Returns the next entry in a symbol table",
        params: params!("table-name" => "Table name", "rewind" => "Optional rewind flag"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "TBLSEARCH",
        signature: "(tblsearch table-name symbol [setnext])",
        description: "Searches a symbol table for a named entry",
        params: params!("table-name" => "Table name", "symbol" => "Entry name", "setnext" => "Optional set next flag"),
        return_type: "list/nil",
        category: Category::Entity,
    },
    // ===== SelectionSet =====
    BuiltinFunction {
        name: "SSGET",
        signature: "(ssget [mode] [pt1 [pt2]] [pt-list] [filter-list])",
        description: "Creates a selection set from entities",
        params: params!("mode" => "Selection mode string", "pt1" => "First point", "pt2" => "Second point", "filter-list" => "Entity filter list"),
        return_type: "selection-set/nil",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSADD",
        signature: "(ssadd [ename [ss]])",
        description: "Adds an entity to a selection set",
        params: params!("ename" => "Entity name", "ss" => "Selection set"),
        return_type: "selection-set",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSDEL",
        signature: "(ssdel ename ss)",
        description: "Removes an entity from a selection set",
        params: params!("ename" => "Entity name", "ss" => "Selection set"),
        return_type: "ename/nil",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSNAME",
        signature: "(ssname ss index)",
        description: "Returns the entity name of the indexed element of a selection set",
        params: params!("ss" => "Selection set", "index" => "Zero-based index"),
        return_type: "ename/nil",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSLENGTH",
        signature: "(sslength ss)",
        description: "Returns the number of entities in a selection set",
        params: params!("ss" => "Selection set"),
        return_type: "integer",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSMEMB",
        signature: "(ssmemb ename ss)",
        description: "Tests whether an entity is a member of a selection set",
        params: params!("ename" => "Entity name", "ss" => "Selection set"),
        return_type: "ename/nil",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSGETFIRST",
        signature: "(ssgetfirst)",
        description: "Returns the current selection set (grips and pickfirst)",
        params: params!(),
        return_type: "list",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSSETFIRST",
        signature: "(sssetfirst gripset [pickset])",
        description: "Sets which entities are selected and gripped",
        params: params!("gripset" => "Grip selection set", "pickset" => "Optional pick selection set"),
        return_type: "list",
        category: Category::SelectionSet,
    },
    BuiltinFunction {
        name: "SSNAMEX",
        signature: "(ssnamex ss [index])",
        description: "Returns selection method and data for each entity in a selection set",
        params: params!("ss" => "Selection set", "index" => "Optional index"),
        return_type: "list",
        category: Category::SelectionSet,
    },
    // ===== Conversion =====
    BuiltinFunction {
        name: "ITOA",
        signature: "(itoa integer)",
        description: "Returns the string conversion of an integer",
        params: params!("integer" => "Integer to convert"),
        return_type: "string",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "ATOI",
        signature: "(atoi string)",
        description: "Returns the integer conversion of a string",
        params: params!("string" => "String to convert"),
        return_type: "integer",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "ATOF",
        signature: "(atof string)",
        description: "Returns the real conversion of a string",
        params: params!("string" => "String to convert"),
        return_type: "real",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "RTOS",
        signature: "(rtos number [mode [precision]])",
        description: "Returns a string representation of a real number",
        params: params!("number" => "Number to convert", "mode" => "Format mode (1-5)", "precision" => "Decimal places"),
        return_type: "string",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "ANGTOS",
        signature: "(angtos angle [mode [precision]])",
        description: "Returns a string representing an angle",
        params: params!("angle" => "Angle in radians", "mode" => "Format mode (0-4)", "precision" => "Decimal places"),
        return_type: "string",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "ANGTOF",
        signature: "(angtof string [mode])",
        description: "Converts a string representing an angle to a real value in radians",
        params: params!("string" => "Angle string", "mode" => "Format mode (0-4)"),
        return_type: "real",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "DISTOF",
        signature: "(distof string [mode])",
        description: "Converts a string representing a distance to a real value",
        params: params!("string" => "Distance string", "mode" => "Format mode (1-5)"),
        return_type: "real",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "TRANS",
        signature: "(trans pt from to [disp])",
        description: "Translates a point from one coordinate system to another",
        params: params!("pt" => "3D point", "from" => "Source coordinate system", "to" => "Destination coordinate system", "disp" => "Optional displacement flag"),
        return_type: "list",
        category: Category::Conversion,
    },
    BuiltinFunction {
        name: "CVUNIT",
        signature: "(cvunit value from to)",
        description: "Converts a value from one unit to another",
        params: params!("value" => "Value to convert", "from" => "Source unit string", "to" => "Destination unit string"),
        return_type: "real/nil",
        category: Category::Conversion,
    },
    // ===== FileIO =====
    BuiltinFunction {
        name: "OPEN",
        signature: "(open filename mode)",
        description: "Opens a file for reading, writing, or appending",
        params: params!("filename" => "File path string", "mode" => "\"r\" read, \"w\" write, \"a\" append"),
        return_type: "file-descriptor/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "CLOSE",
        signature: "(close file-desc)",
        description: "Closes an open file",
        params: params!("file-desc" => "File descriptor"),
        return_type: "nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "READ-LINE",
        signature: "(read-line [file-desc])",
        description: "Reads a line from an open file or keyboard",
        params: params!("file-desc" => "Optional file descriptor"),
        return_type: "string/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "WRITE-LINE",
        signature: "(write-line string [file-desc])",
        description: "Writes a string to a file or screen with a newline",
        params: params!("string" => "String to write", "file-desc" => "Optional file descriptor"),
        return_type: "string",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "READ-CHAR",
        signature: "(read-char [file-desc])",
        description: "Reads a single character from file or keyboard",
        params: params!("file-desc" => "Optional file descriptor"),
        return_type: "integer/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "WRITE-CHAR",
        signature: "(write-char num [file-desc])",
        description: "Writes a character to screen or open file",
        params: params!("num" => "ASCII character code", "file-desc" => "Optional file descriptor"),
        return_type: "integer",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "PRINT",
        signature: "(print expr [file-desc])",
        description: "Prints an expression with a newline prefix and trailing space",
        params: params!("expr" => "Expression to print", "file-desc" => "Optional file descriptor"),
        return_type: "any",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "PRINC",
        signature: "(princ [expr [file-desc]])",
        description: "Prints an expression without extra formatting",
        params: params!("expr" => "Expression to print", "file-desc" => "Optional file descriptor"),
        return_type: "any",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "PRIN1",
        signature: "(prin1 [expr [file-desc]])",
        description: "Prints an expression with strings quoted",
        params: params!("expr" => "Expression to print", "file-desc" => "Optional file descriptor"),
        return_type: "any",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "PROMPT",
        signature: "(prompt msg)",
        description: "Displays a message on the command line",
        params: params!("msg" => "Message string"),
        return_type: "nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "FINDFILE",
        signature: "(findfile filename)",
        description: "Searches the AutoCAD library path for a file",
        params: params!("filename" => "File name to find"),
        return_type: "string/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILENAME-MKTEMP",
        signature: "(vl-filename-mktemp [pattern [directory [extension]]])",
        description: "Creates a unique temporary file name",
        params: params!("pattern" => "Optional name pattern", "directory" => "Optional directory", "extension" => "Optional extension"),
        return_type: "string",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILENAME-DIRECTORY",
        signature: "(vl-filename-directory filename)",
        description: "Returns the directory portion of a file path",
        params: params!("filename" => "File path"),
        return_type: "string",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILENAME-BASE",
        signature: "(vl-filename-base filename)",
        description: "Returns the name portion of a file path without extension",
        params: params!("filename" => "File path"),
        return_type: "string",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILENAME-EXTENSION",
        signature: "(vl-filename-extension filename)",
        description: "Returns the extension portion of a file path",
        params: params!("filename" => "File path"),
        return_type: "string/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-DIRECTORY-FILES",
        signature: "(vl-directory-files [directory [pattern [directories]]])",
        description: "Lists files in a directory",
        params: params!("directory" => "Optional directory path", "pattern" => "Optional wildcard", "directories" => "Optional include dirs flag"),
        return_type: "list/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-COPY",
        signature: "(vl-file-copy source destination [append])",
        description: "Copies a file",
        params: params!("source" => "Source file path", "destination" => "Destination file path", "append" => "Optional append flag"),
        return_type: "integer/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-DELETE",
        signature: "(vl-file-delete filename)",
        description: "Deletes a file",
        params: params!("filename" => "File path to delete"),
        return_type: "T/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-RENAME",
        signature: "(vl-file-rename old-name new-name)",
        description: "Renames a file",
        params: params!("old-name" => "Current file path", "new-name" => "New file path"),
        return_type: "T/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-SIZE",
        signature: "(vl-file-size filename)",
        description: "Returns the size of a file in bytes",
        params: params!("filename" => "File path"),
        return_type: "integer/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-SYSTIME",
        signature: "(vl-file-systime filename)",
        description: "Returns the last modification time of a file",
        params: params!("filename" => "File path"),
        return_type: "list/nil",
        category: Category::FileIO,
    },
    BuiltinFunction {
        name: "VL-FILE-DIRECTORY-P",
        signature: "(vl-file-directory-p name)",
        description: "Tests whether a name refers to a directory",
        params: params!("name" => "Path to test"),
        return_type: "T/nil",
        category: Category::FileIO,
    },
    // ===== Display =====
    BuiltinFunction {
        name: "ALERT",
        signature: "(alert string)",
        description: "Displays an alert dialog box with a message",
        params: params!("string" => "Message to display"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "TEXTSCR",
        signature: "(textscr)",
        description: "Switches to the text screen",
        params: params!(),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "GRAPHSCR",
        signature: "(graphscr)",
        description: "Switches to the graphics screen",
        params: params!(),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "REDRAW",
        signature: "(redraw [ename [mode]])",
        description: "Redraws the current viewport or a specified entity",
        params: params!("ename" => "Optional entity name", "mode" => "Optional mode (1-4)"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "GRDRAW",
        signature: "(grdraw from to color [highlight])",
        description: "Draws a vector on the graphics screen",
        params: params!("from" => "Start point", "to" => "End point", "color" => "Color number", "highlight" => "Optional highlight flag"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "GRTEXT",
        signature: "(grtext [box text [highlight]])",
        description: "Writes text in the status line or screen menu",
        params: params!("box" => "Box number", "text" => "Text string", "highlight" => "Optional highlight flag"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "GRVECS",
        signature: "(grvecs vlist [trans])",
        description: "Draws multiple vectors on the graphics screen",
        params: params!("vlist" => "Vector list", "trans" => "Optional transformation matrix"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "GRREAD",
        signature: "(grread [track [allkeys [curtype]]])",
        description: "Reads input directly from the input device",
        params: params!("track" => "Optional tracking flag", "allkeys" => "Optional all keys flag", "curtype" => "Optional cursor type"),
        return_type: "list",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "MENUCMD",
        signature: "(menucmd string)",
        description: "Issues menu commands",
        params: params!("string" => "Menu command string"),
        return_type: "nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "VPORTS",
        signature: "(vports)",
        description: "Returns a list of viewport descriptors for the current viewport configuration",
        params: params!(),
        return_type: "list",
        category: Category::Display,
    },
    // ===== Geometry =====
    BuiltinFunction {
        name: "ANGLE",
        signature: "(angle pt1 pt2)",
        description: "Returns the angle in radians from pt1 to pt2",
        params: params!("pt1" => "First point", "pt2" => "Second point"),
        return_type: "real",
        category: Category::Geometry,
    },
    BuiltinFunction {
        name: "DISTANCE",
        signature: "(distance pt1 pt2)",
        description: "Returns the distance between two points",
        params: params!("pt1" => "First point", "pt2" => "Second point"),
        return_type: "real",
        category: Category::Geometry,
    },
    BuiltinFunction {
        name: "POLAR",
        signature: "(polar pt angle distance)",
        description: "Returns a point at a given angle and distance from a point",
        params: params!("pt" => "Base point", "angle" => "Angle in radians", "distance" => "Distance"),
        return_type: "list",
        category: Category::Geometry,
    },
    BuiltinFunction {
        name: "INTERS",
        signature: "(inters pt1 pt2 pt3 pt4 [onseg])",
        description: "Finds the intersection of two lines",
        params: params!("pt1" => "First line start", "pt2" => "First line end", "pt3" => "Second line start", "pt4" => "Second line end", "onseg" => "Optional on-segment flag"),
        return_type: "list/nil",
        category: Category::Geometry,
    },
    BuiltinFunction {
        name: "OSNAP",
        signature: "(osnap pt mode)",
        description: "Returns a point found by applying object snap modes",
        params: params!("pt" => "Point", "mode" => "Object snap mode string"),
        return_type: "list/nil",
        category: Category::Geometry,
    },
    BuiltinFunction {
        name: "TEXTBOX",
        signature: "(textbox elist)",
        description: "Returns the bounding box of a text entity",
        params: params!("elist" => "Text entity association list"),
        return_type: "list",
        category: Category::Geometry,
    },
    // ===== ControlFlow =====
    BuiltinFunction {
        name: "IF",
        signature: "(if test-expr then-expr [else-expr])",
        description: "Conditionally evaluates expressions",
        params: params!("test-expr" => "Test expression", "then-expr" => "Expression if true", "else-expr" => "Optional expression if false"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "COND",
        signature: "(cond (test-expr result-expr ...) ...)",
        description: "Evaluates conditional expressions like a multi-branch if",
        params: params!("test-expr" => "Test expression", "result-expr" => "Result expressions"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "PROGN",
        signature: "(progn expr ...)",
        description: "Evaluates each expression sequentially and returns the last value",
        params: params!("expr" => "Expressions to evaluate"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "REPEAT",
        signature: "(repeat count expr ...)",
        description: "Evaluates expressions a specified number of times",
        params: params!("count" => "Number of iterations", "expr" => "Expressions to repeat"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "WHILE",
        signature: "(while test-expr body ...)",
        description: "Evaluates body expressions while test is true",
        params: params!("test-expr" => "Test expression", "body" => "Body expressions"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "AND",
        signature: "(and expr ...)",
        description: "Returns T if all expressions are non-nil",
        params: params!("expr" => "Expressions to test"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "OR",
        signature: "(or expr ...)",
        description: "Returns T if any expression is non-nil",
        params: params!("expr" => "Expressions to test"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "NOT",
        signature: "(not expr)",
        description: "Returns T if expr is nil, nil otherwise",
        params: params!("expr" => "Expression to test"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "EQUAL",
        signature: "(equal expr1 expr2 [fuzz])",
        description: "Tests whether two expressions are equal (with optional tolerance)",
        params: params!("expr1" => "First expression", "expr2" => "Second expression", "fuzz" => "Optional tolerance for reals"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "EQ",
        signature: "(eq expr1 expr2)",
        description: "Tests whether two expressions are identical (same object)",
        params: params!("expr1" => "First expression", "expr2" => "Second expression"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "/=",
        signature: "(/= atom1 atom2)",
        description: "Tests whether two atoms are not equal",
        params: params!("atom1" => "First atom", "atom2" => "Second atom"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "<",
        signature: "(< atom1 atom2 ...)",
        description: "Tests whether each argument is less than the next",
        params: params!("atom" => "Atoms to compare"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: ">",
        signature: "(> atom1 atom2 ...)",
        description: "Tests whether each argument is greater than the next",
        params: params!("atom" => "Atoms to compare"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "<=",
        signature: "(<= atom1 atom2 ...)",
        description: "Tests whether each argument is less than or equal to the next",
        params: params!("atom" => "Atoms to compare"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: ">=",
        signature: "(>= atom1 atom2 ...)",
        description: "Tests whether each argument is greater than or equal to the next",
        params: params!("atom" => "Atoms to compare"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "=",
        signature: "(= atom1 atom2 ...)",
        description: "Tests whether all arguments are numerically equal",
        params: params!("atom" => "Atoms to compare"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "SETQ",
        signature: "(setq sym1 expr1 [sym2 expr2] ...)",
        description: "Sets the value of symbols",
        params: params!("sym" => "Symbol name", "expr" => "Value expression"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "DEFUN",
        signature: "(defun name (params / locals) body ...)",
        description: "Defines a function",
        params: params!("name" => "Function name", "params" => "Parameter list", "body" => "Function body"),
        return_type: "symbol",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "EVAL",
        signature: "(eval expr)",
        description: "Evaluates an AutoLISP expression",
        params: params!("expr" => "Expression to evaluate"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "QUOTE",
        signature: "(quote expr)",
        description: "Returns an expression unevaluated",
        params: params!("expr" => "Expression"),
        return_type: "any",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "COMMAND",
        signature: "(command [cmdname [arguments ...]])",
        description: "Executes an AutoCAD command",
        params: params!("cmdname" => "Command name string", "arguments" => "Command arguments"),
        return_type: "nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "VL-CATCH-ALL-APPLY",
        signature: "(vl-catch-all-apply function arguments)",
        description: "Applies a function with error trapping",
        params: params!("function" => "Function to apply", "arguments" => "Argument list"),
        return_type: "any",
        category: Category::ErrorHandling,
    },
    BuiltinFunction {
        name: "VL-CATCH-ALL-ERROR-P",
        signature: "(vl-catch-all-error-p object)",
        description: "Tests whether an object is an error object from vl-catch-all-apply",
        params: params!("object" => "Object to test"),
        return_type: "T/nil",
        category: Category::ErrorHandling,
    },
    BuiltinFunction {
        name: "VL-CATCH-ALL-ERROR-MESSAGE",
        signature: "(vl-catch-all-error-message error-object)",
        description: "Returns the error message from an error object",
        params: params!("error-object" => "Error object"),
        return_type: "string",
        category: Category::ErrorHandling,
    },
    // ===== TypeChecking =====
    BuiltinFunction {
        name: "TYPE",
        signature: "(type item)",
        description: "Returns the type of item (INT, REAL, STR, SYM, LIST, etc.)",
        params: params!("item" => "Item to check"),
        return_type: "symbol",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "LISTP",
        signature: "(listp item)",
        description: "Returns T if item is a list",
        params: params!("item" => "Item to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "ATOM",
        signature: "(atom item)",
        description: "Returns T if item is an atom (not a list)",
        params: params!("item" => "Item to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "NUMBERP",
        signature: "(numberp item)",
        description: "Returns T if item is a number (integer or real)",
        params: params!("item" => "Item to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "NULL",
        signature: "(null item)",
        description: "Returns T if item is nil",
        params: params!("item" => "Item to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "BOUNDP",
        signature: "(boundp sym)",
        description: "Returns T if sym is bound to a value",
        params: params!("sym" => "Symbol to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "VL-SYMBOLP",
        signature: "(vl-symbolp object)",
        description: "Tests whether an object is a symbol",
        params: params!("object" => "Object to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    BuiltinFunction {
        name: "VL-CONSP",
        signature: "(vl-consp object)",
        description: "Tests whether an object is a non-nil list (cons cell)",
        params: params!("object" => "Object to test"),
        return_type: "T/nil",
        category: Category::TypeChecking,
    },
    // ===== UserInput =====
    BuiltinFunction {
        name: "GETPOINT",
        signature: "(getpoint [pt] [msg])",
        description: "Pauses for user to input a point",
        params: params!("pt" => "Optional base point for rubber-band", "msg" => "Optional prompt string"),
        return_type: "list/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETINT",
        signature: "(getint [msg])",
        description: "Pauses for user to input an integer",
        params: params!("msg" => "Optional prompt string"),
        return_type: "integer/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETREAL",
        signature: "(getreal [msg])",
        description: "Pauses for user to input a real number",
        params: params!("msg" => "Optional prompt string"),
        return_type: "real/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETSTRING",
        signature: "(getstring [cr] [msg])",
        description: "Pauses for user to input a string",
        params: params!("cr" => "Optional allow-spaces flag", "msg" => "Optional prompt string"),
        return_type: "string",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETDIST",
        signature: "(getdist [pt] [msg])",
        description: "Pauses for user to input a distance",
        params: params!("pt" => "Optional base point", "msg" => "Optional prompt string"),
        return_type: "real/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETANGLE",
        signature: "(getangle [pt] [msg])",
        description: "Pauses for user to input an angle",
        params: params!("pt" => "Optional base point", "msg" => "Optional prompt string"),
        return_type: "real/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETCORNER",
        signature: "(getcorner pt [msg])",
        description: "Pauses for user to input the corner of a rectangle",
        params: params!("pt" => "Base corner point", "msg" => "Optional prompt string"),
        return_type: "list/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETKWORD",
        signature: "(getkword [msg])",
        description: "Pauses for user to input a keyword",
        params: params!("msg" => "Optional prompt string"),
        return_type: "string/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETVAR",
        signature: "(getvar varname)",
        description: "Returns the value of an AutoCAD system variable",
        params: params!("varname" => "System variable name"),
        return_type: "any",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "SETVAR",
        signature: "(setvar varname value)",
        description: "Sets the value of an AutoCAD system variable",
        params: params!("varname" => "System variable name", "value" => "New value"),
        return_type: "any",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETENV",
        signature: "(getenv varname)",
        description: "Returns the value of an environment variable",
        params: params!("varname" => "Environment variable name"),
        return_type: "string/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "SETENV",
        signature: "(setenv varname value)",
        description: "Sets the value of an environment variable",
        params: params!("varname" => "Environment variable name", "value" => "Value string"),
        return_type: "string",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "GETFILED",
        signature: "(getfiled title default ext flags)",
        description: "Displays a file dialog box and returns the selected file name",
        params: params!("title" => "Dialog title", "default" => "Default file name", "ext" => "Default extension", "flags" => "Behavior flags"),
        return_type: "string/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "INITGET",
        signature: "(initget [bits] [string])",
        description: "Initializes keywords and bit flags for the next user input function",
        params: params!("bits" => "Optional control bits", "string" => "Optional keyword string"),
        return_type: "nil",
        category: Category::UserInput,
    },
    // ===== Symbol =====
    BuiltinFunction {
        name: "SET",
        signature: "(set sym expr)",
        description: "Sets the value of a quoted symbol",
        params: params!("sym" => "Quoted symbol", "expr" => "Value expression"),
        return_type: "any",
        category: Category::Symbol,
    },
    BuiltinFunction {
        name: "READ",
        signature: "(read string)",
        description: "Returns the first expression from a string",
        params: params!("string" => "String to read"),
        return_type: "any",
        category: Category::Symbol,
    },
    BuiltinFunction {
        name: "ATOMS-FAMILY",
        signature: "(atoms-family format [symlist])",
        description: "Returns a list of currently defined symbols",
        params: params!("format" => "0=symbols, 1=strings", "symlist" => "Optional symbol list to check"),
        return_type: "list",
        category: Category::Symbol,
    },
    BuiltinFunction {
        name: "VL-SYMBOL-NAME",
        signature: "(vl-symbol-name symbol)",
        description: "Returns the name of a symbol as a string",
        params: params!("symbol" => "Symbol"),
        return_type: "string",
        category: Category::Symbol,
    },
    BuiltinFunction {
        name: "VL-SYMBOL-VALUE",
        signature: "(vl-symbol-value symbol)",
        description: "Returns the value bound to a symbol",
        params: params!("symbol" => "Symbol"),
        return_type: "any",
        category: Category::Symbol,
    },
    // ===== Misc =====
    BuiltinFunction {
        name: "LOAD",
        signature: "(load filename [onfailure])",
        description: "Loads an AutoLISP file",
        params: params!("filename" => "File path", "onfailure" => "Optional failure return value"),
        return_type: "any",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-LOAD-ALL",
        signature: "(vl-load-all filename)",
        description: "Loads an AutoLISP file into all open documents",
        params: params!("filename" => "File path"),
        return_type: "T/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "STARTAPP",
        signature: "(startapp appcmd [file])",
        description: "Starts an external application",
        params: params!("appcmd" => "Application command", "file" => "Optional file argument"),
        return_type: "integer",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VER",
        signature: "(ver)",
        description: "Returns a string containing the AutoLISP version number",
        params: params!(),
        return_type: "string",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "ARXLOAD",
        signature: "(arxload application [onfailure])",
        description: "Loads an ARX/BRX application",
        params: params!("application" => "Application file path", "onfailure" => "Optional failure return"),
        return_type: "string/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "ARXUNLOAD",
        signature: "(arxunload application [onfailure])",
        description: "Unloads an ARX/BRX application",
        params: params!("application" => "Application name", "onfailure" => "Optional failure return"),
        return_type: "string/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "AUTOLOAD",
        signature: "(autoload filename cmdlist)",
        description: "Defines commands that automatically load a file when first used",
        params: params!("filename" => "File to load", "cmdlist" => "List of command names"),
        return_type: "nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-BB-REF",
        signature: "(vl-bb-ref symbol)",
        description: "Returns the value of a blackboard variable",
        params: params!("symbol" => "Variable name"),
        return_type: "any",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-BB-SET",
        signature: "(vl-bb-set symbol value)",
        description: "Sets a blackboard variable",
        params: params!("symbol" => "Variable name", "value" => "Value to set"),
        return_type: "any",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-PROPAGATE",
        signature: "(vl-propagate symbol)",
        description: "Copies the value of a variable to all open document namespaces",
        params: params!("symbol" => "Variable name"),
        return_type: "T",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-LOAD-COM",
        signature: "(vl-load-com)",
        description: "Loads the Visual LISP COM support functions",
        params: params!(),
        return_type: "nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-REGISTRY-READ",
        signature: "(vl-registry-read key [value-name])",
        description: "Returns a value from the Windows registry",
        params: params!("key" => "Registry key path", "value-name" => "Optional value name"),
        return_type: "string/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-REGISTRY-WRITE",
        signature: "(vl-registry-write key [value-name [value]])",
        description: "Creates or modifies a Windows registry value",
        params: params!("key" => "Registry key path", "value-name" => "Optional value name", "value" => "Optional value"),
        return_type: "T/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-REGISTRY-DELETE",
        signature: "(vl-registry-delete key [value-name])",
        description: "Deletes a registry key or value",
        params: params!("key" => "Registry key path", "value-name" => "Optional value name"),
        return_type: "T/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-REGISTRY-DESCENDENTS",
        signature: "(vl-registry-descendents key [value-names])",
        description: "Returns sub-keys or value names of a registry key",
        params: params!("key" => "Registry key path", "value-names" => "Optional flag for value names"),
        return_type: "list/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "GETCFG",
        signature: "(getcfg cfgname)",
        description: "Retrieves application data from the AppData section of acad.cfg",
        params: params!("cfgname" => "Config path string"),
        return_type: "string/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "SETCFG",
        signature: "(setcfg cfgname value)",
        description: "Writes application data to the AppData section of acad.cfg",
        params: params!("cfgname" => "Config path string", "value" => "Value string"),
        return_type: "string/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "NAMEDOBJDICT",
        signature: "(namedobjdict)",
        description: "Returns the entity name of the Named Object Dictionary",
        params: params!(),
        return_type: "ename",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "DICTSEARCH",
        signature: "(dictsearch ename symbol [setnext])",
        description: "Searches a dictionary for an entry",
        params: params!("ename" => "Dictionary entity name", "symbol" => "Entry name", "setnext" => "Optional set next flag"),
        return_type: "list/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "DICTADD",
        signature: "(dictadd ename symbol newobj)",
        description: "Adds a non-graphical object to a dictionary",
        params: params!("ename" => "Dictionary entity name", "symbol" => "Entry key", "newobj" => "Entity name of new object"),
        return_type: "ename",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "DICTNEXT",
        signature: "(dictnext ename [rewind])",
        description: "Returns the next entry in a dictionary",
        params: params!("ename" => "Dictionary entity name", "rewind" => "Optional rewind flag"),
        return_type: "list/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "DICTREMOVE",
        signature: "(dictremove ename symbol)",
        description: "Removes an entry from a dictionary",
        params: params!("ename" => "Dictionary entity name", "symbol" => "Entry key"),
        return_type: "ename/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "DICTRENAME",
        signature: "(dictrename ename oldsym newsym)",
        description: "Renames a dictionary entry",
        params: params!("ename" => "Dictionary entity name", "oldsym" => "Old key", "newsym" => "New key"),
        return_type: "ename/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "REGAPP",
        signature: "(regapp application)",
        description: "Registers an application name for extended entity data",
        params: params!("application" => "Application name string"),
        return_type: "application/nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "XDROOM",
        signature: "(xdroom ename)",
        description: "Returns the amount of xdata space available for an entity",
        params: params!("ename" => "Entity name"),
        return_type: "integer",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "XDSIZE",
        signature: "(xdsize list)",
        description: "Returns the size of an xdata list",
        params: params!("list" => "Xdata list"),
        return_type: "integer",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "TRACE",
        signature: "(trace func ...)",
        description: "Enables trace debugging for the specified functions",
        params: params!("func" => "Function names to trace"),
        return_type: "nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "UNTRACE",
        signature: "(untrace func ...)",
        description: "Disables trace debugging for the specified functions",
        params: params!("func" => "Function names to untrace"),
        return_type: "nil",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "LAMBDA",
        signature: "(lambda (params) body ...)",
        description: "Defines an anonymous function",
        params: params!("params" => "Parameter list", "body" => "Function body"),
        return_type: "function",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "DEFUN-Q",
        signature: "(defun-q name (params / locals) body ...)",
        description: "Defines a function as a list (quotable)",
        params: params!("name" => "Function name", "params" => "Parameter list", "body" => "Function body"),
        return_type: "symbol",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "VL-ACAD-DEFUN",
        signature: "(vl-acad-defun symbol)",
        description: "Makes a function available to ObjectARX",
        params: params!("symbol" => "Function symbol"),
        return_type: "integer",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-ACAD-UNDEFUN",
        signature: "(vl-acad-undefun symbol)",
        description: "Removes a function from ObjectARX interface",
        params: params!("symbol" => "Function symbol"),
        return_type: "integer",
        category: Category::Misc,
    },
    BuiltinFunction {
        name: "VL-EXIT-WITH-ERROR",
        signature: "(vl-exit-with-error msg)",
        description: "Passes control to the *error* function",
        params: params!("msg" => "Error message string"),
        return_type: "nil",
        category: Category::ErrorHandling,
    },
    BuiltinFunction {
        name: "VL-EXIT-WITH-VALUE",
        signature: "(vl-exit-with-value value)",
        description: "Returns a value to the calling application",
        params: params!("value" => "Return value"),
        return_type: "any",
        category: Category::ErrorHandling,
    },
    BuiltinFunction {
        name: "COMMAND-S",
        signature: "(command-s cmdname [arguments ...])",
        description: "Executes an AutoCAD command synchronously (no pause allowed)",
        params: params!("cmdname" => "Command name string", "arguments" => "Command arguments"),
        return_type: "nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "VL-CMDF",
        signature: "(vl-cmdf cmdname [arguments ...])",
        description: "Executes an AutoCAD command and validates arguments",
        params: params!("cmdname" => "Command name string", "arguments" => "Command arguments"),
        return_type: "T/nil",
        category: Category::ControlFlow,
    },
    BuiltinFunction {
        name: "GETORIENT",
        signature: "(getorient [pt] [msg])",
        description: "Pauses for user to input an angle (uses ANGBASE/ANGDIR)",
        params: params!("pt" => "Optional base point", "msg" => "Optional prompt string"),
        return_type: "real/nil",
        category: Category::UserInput,
    },
    BuiltinFunction {
        name: "CAAAR",
        signature: "(caaar list)",
        description: "Equivalent to (car (car (car list)))",
        params: params!("list" => "A nested list"),
        return_type: "any",
        category: Category::List,
    },
    BuiltinFunction {
        name: "CDAAR",
        signature: "(cdaar list)",
        description: "Equivalent to (cdr (car (car list)))",
        params: params!("list" => "A nested list"),
        return_type: "list",
        category: Category::List,
    },
    BuiltinFunction {
        name: "VL-MEMBER-IF-NOT",
        signature: "(vl-member-if-not predicate list)",
        description: "Returns list from first element not satisfying predicate",
        params: params!("predicate" => "Test function", "list" => "Source list"),
        return_type: "list/nil",
        category: Category::List,
    },
    BuiltinFunction {
        name: "MENUGROUP",
        signature: "(menugroup groupname)",
        description: "Verifies that a menu group is loaded",
        params: params!("groupname" => "Menu group name"),
        return_type: "string/nil",
        category: Category::Display,
    },
    BuiltinFunction {
        name: "VLAX-ENAME->VLA-OBJECT",
        signature: "(vlax-ename->vla-object ename)",
        description: "Converts an entity name to a VLA object",
        params: params!("ename" => "Entity name"),
        return_type: "vla-object",
        category: Category::Entity,
    },
    BuiltinFunction {
        name: "VLAX-VLA-OBJECT->ENAME",
        signature: "(vlax-vla-object->ename vla-object)",
        description: "Converts a VLA object to an entity name",
        params: params!("vla-object" => "VLA object"),
        return_type: "ename",
        category: Category::Entity,
    },
];
